name: Deploy Flutter Web

# Events that trigger the workflow
on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allow manual triggering of the workflow

# Define jobs
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Step 3: Build the Flutter web app
      - name: Build Flutter Web
        run: flutter build web

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: FerasAbushahla/cengreen_website
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web

